### ISSUE TITLE
Update for GNOME 3.18

### ISSUE THREAD

**Issue by kparal** [laserb/gnome-shell-extension-suspend-button#11]
Hello,

GNOME 3.18 has been released and many people already use it. Could you please update your extension at extensions.gnome.org to support this new GNOME version?

Thanks!

**Comment by ainola** [comment]
I'd love an update, too!

**Comment by Selena-Gomez** [comment]
I too, would greatly appreciate an update :+1:

**Comment by coldtobi** [comment]
Hi laserb,

This has also been reported in Debian, and the one reporting it provided also a patch. Maybe you want to take a look on it: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801645

Thanks!

tobi

**Comment by Eelviny** [comment]
+1 to this, would love an update :+1:

**Comment by fnkr** [comment]
Me too!

+1

**Comment by mardiros** [comment]
Every MR forgot to update the README.md but update the metadata.json is welcome.

**Comment by laserb** [comment]
Thanks. Was busy lately. Now it is added. Better late than never...
