### ISSUE TITLE
Please update to 3.20

### ISSUE THREAD

**Issue by genodeftest** [laserb/gnome-shell-extension-suspend-button#16]
This extension works fine on Gnome 3.20. Please update it to extensions.gnome.org.

Thanks for the nice work!

**Comment by ZhengshuaiPENG** [comment]
@genodeftest after update from 3.18 to Gnome 3.20, this extension currently does not work, it works on you Gnome 3.20?

**Comment by orffen** [comment]
This doesn't work for me on 3.20 - any chance of an update to support 3.20?

**Comment by genodeftest** [comment]
After just changing the version in metadata.json to 3.20 it works fine for me.

**Comment by se1exin** [comment]
Work fine for me on Arch Linux Gnome 3.20. Just created pull request for 3.20 compatibility: https://github.com/laserb/gnome-shell-extension-suspend-button/pull/17
