### ISSUE TITLE
does not work with arch-gnome

### ISSUE THREAD

**Issue by tatsujb** [laserb/gnome-shell-extension-suspend-button#21]
how are we to install this on arch?

**Comment by laserb** [comment]
You can try the package in aur: https://aur.archlinux.org/packages/gnome-shell-extension-suspend-button-git/

**Comment by laserb** [comment]
or via the gnome extension website: https://extensions.gnome.org/extension/826/suspend-button/

**Comment by laserb** [comment]
There was an error in the version string that is fixed now, so please try again

**Comment by tatsujb** [comment]
i downloaded the new version i tried the alternative build (with sudo) and rebooted but still nothing.

what could i be missing?

**Comment by cedricbrx** [comment]
same problem for me on gnome 3.22, Debian Stretch

**Comment by coldtobi** [comment]
cedickbrx: It works for me on Debian Stretch. Did you update recently? (You need to ensure to hve gnome-shell 3.22 otherwise or disable the version check for extensions in gnome-shell)
Did you install the Debian package?
