### ISSUE TITLE
Make script falied to be executed

### ISSUE THREAD

**Issue by androidovshchik** [laserb/gnome-shell-extension-suspend-button#23]
Hi
I tried to install this extension, but failed with make command
I run:
`$ make`
And the output is:
`UUID is "suspend-button@laserb"`
`make: Nothing to be done for 'all'.`
Please, help with the issue
My operation system is Debian 8.8 with Gnome 3.14.1

**Comment by Cloverii** [comment]
The same problem
Ubuntu 16.04, GNOME 3.18.5

**Comment by laserb** [comment]
The output says that nothingbhas to be done for 'all'. So it already did that.   
Are you trying to build a zip file? Try running ’make zip-file’ then.

**Comment by laserb** [comment]
Or ‘make install’ if you try to install it.

**Comment by laserb** [comment]
You can install it via the gnome-shell extensions webpage as well.

**Comment by Cloverii** [comment]
Thank you, now I know it has been built and only 'make install' is needed.

**Comment by mr-cpp** [comment]
Sorry
I understood
Simply i have not enough experience with Linux OS
