### ISSUE TITLE
Bluetooth thrashed

### ISSUE THREAD

**Issue by landrykid** [laserb/gnome-shell-extension-suspend-button#26]
I did a fresh install of Debian 9.1 with GNOME, after which my bluetooth keyboard and mouse "just worked".  I installed the "Suspend Button" extension, tried it once, and found after waking up my computer that bluetooth no longer worked.  I uninstalled the extension, but cannot turn on bluetooth via "Settings", the panel drop-down, restarting the service via the command line, or restarting the computer.

**Comment by laserb** [comment]
I don't think this is related to the extension. It does not change anything that is related to bluetooth or even your command line. It is just a visual change for gnome.     
But sometimes bluetooth devices do not wake up properly after suspend. This seems to be the case here as you have problems restarting the service. Usually the bluetooth device works again after a reboot. I recommend to investigate more in problems related to your bluetooth device.
