### ISSUE TITLE
Broken in Gnome 3.26.1 (antergos)

### ISSUE THREAD

**Issue by izznogooood** [laserb/gnome-shell-extension-suspend-button#28]
No errors, but buttons dont do anything

Please let me know if I cant help.

**Comment by laserb** [comment]
Are you sure it is version 3.2.1? That would be pretty old. Current version is 3.26.   
This could be related to #30

**Comment by izznogooood** [comment]
No, its 3.26.1 ;)

**Comment by laserb** [comment]
Ok, then it is a duplicate of #30.
