### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by solrac156** [laserb/gnome-shell-extension-suspend-button#30]
Hi, I just installed this extension in my computer, and it's not working. I'm running a Debian 9 OS with Gnome 3.22. The installation seems like it went fine, no compiler errors, but it's still not working.

**Comment by coldtobi** [comment]
Am 22. Oktober 2017 21:44:23 MESZ schrieb solrac156 <notifications@github.com>:
>Hi, I just installed this extension in my computer, and it's not
>working. I'm running a Debian 9 OS with Gnome 3.22. The installation
>seems like it went fine, no compiler errors, but it's still not
>working.

Did you use the Debian package or did you install manually?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by diraimondo** [comment]
I'm using the installation of the extension by means of the browser and it is not working for me on gnome shell 3.26.1.

```
 head ~/.local/share/gnome-shell/extensions/suspend-button@laserb/README.md | grep GNOME   
GNOME Shell Extension Suspend-Button for GNOME 3.10 / 3.12 / 3.14 / 3.16 / 3.18 / 3.20 / 3.22 / 3.24 / 3.26
```

**Comment by psyray** [comment]
On gnome 3.26 error reported is
```
JS ERROR: TypeError: this.systemMenu._onPowerOffClicked is not a function#012Extension<._onPowerOffClicked@/home/user/.local/share/gnome-shell/extensions/suspend-button@laserb/extension.js:188:9#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```

**Comment by laserb** [comment]
Thanks a lot for the js error. The version check fails. I will fix it.

**Comment by psyray** [comment]
I have updated your extension from the my exyension page of the gnome website, after an ubuntu 17.10 upgrade from 17.04, error above was reported.

So I updated to latest (from extension page download the 3.26 -> 18) by replacing files in `~/.local/share/gnome-shell/extensions/suspend-button@laserb` with downloaded archive contents, it works :+1: 

Don't know why the update from my extensions page does not work.

**Comment by solrac156** [comment]
I did the installation manually with the instructions on the README file.

**Comment by laserb** [comment]
I updated it. It will be available on the gnome shell extension page soon.

**Comment by psyray** [comment]
:+1:

**Comment by solrac156** [comment]
I pulled the repo, compiled and installed and it's still not working

**Comment by laserb** [comment]
New version is now available via extensions.gnome.org

**Comment by laserb** [comment]
@solrac156 What is not working? I tested it with Gnome 9 Live Image (Gnome 3.22.3) and it is working on my side.

**Comment by solrac156** [comment]
The button is not appearing where it should be, after I installed it, seems like there's no change at all
