### ISSUE TITLE
Please tag new versions / releases, when uploading to extensions.gnome.org

### ISSUE THREAD

**Issue by besser82** [laserb/gnome-shell-extension-suspend-button#33]
Hello,

I want to package your extension for Fedora and EPEL.  The fact there are no versions or releases tagged in your repo, makes it difficult to automagically track updates…

Cheers,
  Björn

**Comment by laserb** [comment]
I tagged the current version for 3.34 as v2.0 and for older versions as v1.0.
I will try to create new tags for the next versions.
