### ISSUE TITLE
Screen lock

### ISSUE THREAD

**Issue by sabian2008** [laserb/gnome-shell-extension-suspend-button#36]
Hi!
Great extension, have been using it for years now!

It occurred to me that it might be useful to have the option to toggle screen locking while suspending. I tried it to hack it myself but I haven't been able to determine how the extension interfaces with the power management system (i.e. what command actually gets called).

Do you have any hints?

Cheers,

**Comment by laserb** [comment]
The extension uses the suspend mechanism of gnome itself. So the behaviour should be the same.   
You can try disabling the extension and check if the screen is locked there. If it is not locked, then you need to check your gnome settings.

**Comment by sabian2008** [comment]
Thanks for the hint. My problem was that I wanted screen to get locked only when suspending, and not by inactivity or screensaver kicking in. That combination I could not get from Gnome's settings, but with the info you provided it was pretty easy to hack it.

You just need to run
```
sudo sh -C <<EOF
export dir=/usr/lib/systemd/system-sleep
echo -e '#!bin/bash\nif [ "${1}" == "pre" ]; then\n\tloginctl lock-sessions\nfi' > $dir/lock_screen.sh                                                                    chmod u+x $dir/lock_screen.sh
EOF
```
To create a script (`lock_screen.sh`) which gets called before `systemctl suspend`  and runs `loginctl lock-sessions` to, as you've guessed it, lock all the sessions.

If you are on Debian based systems, `dir` needs to be changed to `/lib/systemd/system-sleep` I think.
