### ISSUE TITLE
Undefined Action Menu

### ISSUE THREAD

**Issue by mokilcde** [laserb/gnome-shell-extension-suspend-button#41]
Hi!

I got the following message after updating to Gnome Shell version 3.33.90:
gnome-shell[2532]: JS WARNING: [/srv/home/michael/.local/share/gnome-shell/extensions/suspend-button@laserb/extension.js 174]: reference to undefined property "_actionsItem"
gnome-shell[2532]: Extension "suspend-button@laserb" had error: TypeError: this.systemMenu._actionsItem is undefined

CU
Michael

**Comment by laserb** [comment]
This is fixed with https://github.com/laserb/gnome-shell-extension-suspend-button/pull/43
