### ISSUE TITLE
Support for gnome-shell 3.34

### ISSUE THREAD

**Issue by Norbert01** [laserb/gnome-shell-extension-suspend-button#42]
Please add gnome-shell 3.34

**Comment by laserb** [comment]
Should be fixed now, otherwise please re-open this issue.

**Comment by sheepdestroyer** [comment]
Does not work for me on fedora 31 (just upgraded from 30)
Shows ERROR on extensions.gnome.org
Tried uninstall and reinstall

**Comment by sheepdestroyer** [comment]
It's working this morning!
