### ISSUE TITLE
Please put latest version to extensions.gnome.org

### ISSUE THREAD

**Issue by genodeftest** [laserb/gnome-shell-extension-suspend-button#52]
The site extensions.gnome.org is missing the latest version of this gnome-shell extension. Can you please get it updated there?

**Comment by genodeftest** [comment]
Sorry, something went wrong on my side. After removing and reinstalling it, I got the latest version on my computer.

**Comment by apollo234** [comment]
> The site extensions.gnome.org is missing the latest version of this gnome-shell extension. Can you please get it updated there?
