### ISSUE TITLE
Update extension to the most current versions of Gnome Shell

### ISSUE THREAD

**Issue by erickmajor** [laserb/gnome-shell-extension-suspend-button#8]
Hello laserb,

This extension does not work for Gnome Shell 3.4, unfortunately. Please update this extension to the most current versions.

Thank you very much!

**Comment by laserb** [comment]
Hi erickmajor

The current version of Gnome-Shell is 3.14 not 3.4. This extension does not work for any version before 3.10.
I remember that the [Frippery Shut Down Menu](https://extensions.gnome.org/extension/14/shut-down-menu/) provided a similar functionality for pre 3.10 versions.

**Comment by erickmajor** [comment]
Hello laserb, thanks for the quick response.
![captura de tela de 2015-01-21 12 01 05](https://cloud.githubusercontent.com/assets/5443488/5837427/458e2cc6-a166-11e4-8566-eed2bf4c411e.png)

I think there was a mistake, because the version of my gnome-shell is 3.4.2. Here is a picture of the terminal.

I await your response. Thank U!

**Comment by laserb** [comment]
I think you misunderstood the version numbering of gnome-shell. You are using 3.4 (3.four). But this extension is only for version 3.10 or later (3.ten or later). Most recent version of gnome-shell is 3.14.
So please give the Frippery extension a try.

**Comment by erickmajor** [comment]
Hi laserb,

A lot of apologizing for my mistake. Really confuse me with the number of versions.

Thanks for all the attention.

**Comment by erickmajor** [comment]
Hi laserb,

I've been searching a way to update the Gnome Shell for Debian Wheezy, but all are too complex for that.

There are many differences between the organization of the files for extensions in Gnome 3.4? This task is too complex?

Thank you for your attention.

**Comment by laserb** [comment]
Hi erickmajor

Gnome-Shell has many dependencies that would need to be updated too. Therefore I think the easiest way would be to search a repository that provides the latest gnome version for debian wheezy.
Or wait a bit longer, as debian jessy with gnome 3.14 seems to be coming soon.

Closing this for now.
